language: go

go:
  - 1.8.x
  - 1.9.x

install:
- go get github.com/iotaledger/giota

before_install:
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- export PATH=$PATH:$GOPATH/bin
- export CGO_LDFLAGS_ALLOW='-msse2'
- export CGO_CFLAGS_ALLOW='-msse2 -Wall'
- gometalinter --install --update

script:
- travis_wait 30 go test -tags=avx -v -covermode=count -coverprofile=coverage.out -timeout 100m -short

after_success:
- gometalinter -e bindata --deadline=1000s ./...
- goveralls -coverprofile=coverage.out -service=travis-ci

